/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * ClassViewerForm.java
 *
 * Created on 15-jan-2012, 21:19:42
 */
package net.aurora.sorcery.ui.frame;

import net.aurora.sorcery.ui.panel.ClassViewPanel;
import net.aurora.sorcery.ui.panel.FieldViewPanel;
import serp.bytecode.BCClass;

/**
 *
 * @author Devel
 */
public class ClassViewerForm extends javax.swing.JInternalFrame {

    private BCClass containedClass;

    /** Creates new form ClassViewerForm */
    public ClassViewerForm(BCClass containedClass) {
        initComponents();
        this.containedClass = containedClass;        
        
        this.setTitle(this.getTitle() + " - Viewing: " + containedClass.getName());
        this.classViewTabbedPane.addTab("Class overview", new ClassViewPanel(this));
        this.classViewTabbedPane.addTab("Fields", new FieldViewPanel(this));
        setVisible(true);
    }

    public BCClass getContainedClass() {
        return this.containedClass;
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        classViewTabbedPane = new javax.swing.JTabbedPane();
        jMenuBar1 = new javax.swing.JMenuBar();
        fileMenu = new javax.swing.JMenu();
        exportItem = new javax.swing.JMenuItem();
        editMenu = new javax.swing.JMenu();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);
        setTitle("Spellcaster");

        fileMenu.setText("File");

        exportItem.setText("Export to .class");
        fileMenu.add(exportItem);

        jMenuBar1.add(fileMenu);

        editMenu.setText("Edit");
        jMenuBar1.add(editMenu);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(classViewTabbedPane, javax.swing.GroupLayout.DEFAULT_SIZE, 900, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(classViewTabbedPane, javax.swing.GroupLayout.DEFAULT_SIZE, 547, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTabbedPane classViewTabbedPane;
    private javax.swing.JMenu editMenu;
    private javax.swing.JMenuItem exportItem;
    private javax.swing.JMenu fileMenu;
    private javax.swing.JMenuBar jMenuBar1;
    // End of variables declaration//GEN-END:variables
}
