/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * FieldViewerForm.java
 *
 * Created on 15-jan-2012, 22:49:45
 */
package net.aurora.sorcery.ui.frame;

import java.lang.reflect.Field;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Devel
 */
public class FieldViewerForm extends javax.swing.JInternalFrame {
    
    private Object value;
    private Field field;

    /** Creates new form FieldViewerForm */
    public FieldViewerForm(Field field, Object value) {
        initComponents();
        if (field != null) {
            this.field = field;
            try {
                this.value = this.field.get(null);
            } catch (IllegalArgumentException ex) {
                Logger.getLogger(FieldViewerForm.class.getName()).log(Level.SEVERE, null, ex);
            } catch (IllegalAccessException ex) {
                Logger.getLogger(FieldViewerForm.class.getName()).log(Level.SEVERE, null, ex);
            }
        } else {
            this.value = value;
        }        
        
        this.jTable1.setModel(myFieldValueTableModel);        
        setVisible(true);
    }
    private DefaultTableModel myFieldValueTableModel = new DefaultTableModel() {
        
        private final String[] columns = {"Position", "Type", "Value"};
        
        @Override
        public int getRowCount() {
            return value instanceof Object[] ? ((Object[]) value).length : 1;
        }
        
        @Override
        public int getColumnCount() {
            return 3;
        }
        
        @Override
        public String getColumnName(int columnIndex) {
            return columns[columnIndex];
        }
        
        @Override
        public boolean isCellEditable(int rowIndex, int columnIndex) {
            return false;
        }
        
        @Override
        public Object getValueAt(int rowIndex, int columnIndex) {
            switch (columnIndex) {
                case 0:
                    return rowIndex;
                
                case 1:
                    Object aVal = value;
                    if (value instanceof Object[]) {
                        aVal = ((Object[]) value)[rowIndex];
                    }
                    return aVal.getClass().getSimpleName();
                
                case 2:
                    Object nVal = value;
                    if (value instanceof Object[]) {
                        nVal = ((Object[]) value)[rowIndex];
                    }
                    return String.valueOf(nVal);
                
            }
            return null;
        }
    };

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);
        setTitle("Field expander");

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        jButton1.setText("Expand further");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Refresh");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 557, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(373, 373, 373)
                .addComponent(jButton2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton1))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButton2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 209, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
    ((DefaultTableModel) this.jTable1.getModel()).fireTableDataChanged();
}//GEN-LAST:event_jButton2ActionPerformed
    
private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
    if (value instanceof Object[]) {        
        getParent().add(new FieldViewerForm(null, ((Object[]) value)[this.jTable1.getSelectedRow()]));
    } else if(value instanceof int[]) {
        getParent().add(new FieldViewerForm(null, ((Object[]) value)));
    }
}//GEN-LAST:event_jButton1ActionPerformed
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}
