/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * ClassViewPanel.java
 *
 * Created on 15-jan-2012, 21:35:29
 */
package net.aurora.sorcery.ui.panel;

import net.aurora.sorcery.ui.frame.ClassViewerForm;

/**
 *
 * @author Devel
 */
public class ClassViewPanel extends javax.swing.JPanel {
    private ClassViewerForm parent;
    
    /** Creates new form ClassViewPanel */
    public ClassViewPanel(ClassViewerForm parent) {
        initComponents();
        this.parent = parent;
        
        this.classNameTxt.setText(parent.getContainedClass().getClassName());
        this.superClassNameTxt.setText(parent.getContainedClass().getSuperclassName());
        this.abstractTxt.setText(String.valueOf(parent.getContainedClass().isAbstract()));
        this.interfaceTxt.setText(String.valueOf(parent.getContainedClass().isInterface()));
        this.enumTxt.setText(String.valueOf(parent.getContainedClass().isEnum()));
        this.fieldCountTxt.setText(String.valueOf(parent.getContainedClass().getFields().length));
        this.methodCountTxt.setText(String.valueOf(parent.getContainedClass().getMethods().length));
        
        String[] interfaces = parent.getContainedClass().getInterfaceNames();
        String interfacesConcat = "";
        for(int i = 0; i < interfaces.length; i++) {
            if(i != interfaces.length - 1) {
                interfacesConcat += interfaces[i] + ", ";
            } else {
                interfacesConcat += interfaces[i];
            }
        }
        this.interfacesTxt.setText(interfacesConcat);
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        methodCountTxt = new javax.swing.JLabel();
        fieldCountTxt = new javax.swing.JLabel();
        interfacesTxt = new javax.swing.JLabel();
        enumTxt = new javax.swing.JLabel();
        interfaceTxt = new javax.swing.JLabel();
        abstractTxt = new javax.swing.JLabel();
        superClassNameTxt = new javax.swing.JLabel();
        classNameTxt = new javax.swing.JLabel();
        methodCountLbl = new javax.swing.JLabel();
        abstractLbl = new javax.swing.JLabel();
        classNameLbl = new javax.swing.JLabel();
        interfaceLbl = new javax.swing.JLabel();
        enumLbl = new javax.swing.JLabel();
        interfacesLbl = new javax.swing.JLabel();
        fieldCountLbl = new javax.swing.JLabel();
        superClassNameLbl = new javax.swing.JLabel();

        methodCountTxt.setText("jLabel1");

        fieldCountTxt.setText("jLabel1");

        interfacesTxt.setText("jLabel1");

        enumTxt.setText("jLabel1");

        interfaceTxt.setText("jLabel1");

        abstractTxt.setText("jLabel1");

        superClassNameTxt.setText("jLabel1");

        classNameTxt.setText("jLabel1");

        methodCountLbl.setText("Method count:");

        abstractLbl.setText("Abstract:");

        classNameLbl.setText("Class name:");

        interfaceLbl.setText("Interface:");

        enumLbl.setText("Enum:");

        interfacesLbl.setText("Interfaces:");

        fieldCountLbl.setText("Field count:");

        superClassNameLbl.setText("Superclass:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 816, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(classNameLbl)
                    .addComponent(superClassNameLbl)
                    .addComponent(abstractLbl)
                    .addComponent(interfaceLbl)
                    .addComponent(enumLbl))
                .addGap(34, 34, 34)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(enumTxt)
                    .addComponent(interfaceTxt)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(classNameTxt)
                            .addComponent(superClassNameTxt)
                            .addComponent(abstractTxt))
                        .addGap(174, 174, 174)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(interfacesLbl)
                            .addComponent(fieldCountLbl)
                            .addComponent(methodCountLbl))
                        .addGap(28, 28, 28)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(methodCountTxt)
                            .addComponent(fieldCountTxt)
                            .addComponent(interfacesTxt))))
                .addContainerGap(374, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 466, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(classNameLbl)
                    .addComponent(interfacesLbl)
                    .addComponent(classNameTxt)
                    .addComponent(interfacesTxt))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(superClassNameLbl)
                    .addComponent(fieldCountLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(superClassNameTxt)
                    .addComponent(fieldCountTxt))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(abstractLbl)
                    .addComponent(methodCountLbl)
                    .addComponent(abstractTxt)
                    .addComponent(methodCountTxt))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(interfaceLbl)
                    .addComponent(interfaceTxt))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(enumLbl)
                    .addComponent(enumTxt))
                .addContainerGap(361, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel abstractLbl;
    private javax.swing.JLabel abstractTxt;
    private javax.swing.JLabel classNameLbl;
    private javax.swing.JLabel classNameTxt;
    private javax.swing.JLabel enumLbl;
    private javax.swing.JLabel enumTxt;
    private javax.swing.JLabel fieldCountLbl;
    private javax.swing.JLabel fieldCountTxt;
    private javax.swing.JLabel interfaceLbl;
    private javax.swing.JLabel interfaceTxt;
    private javax.swing.JLabel interfacesLbl;
    private javax.swing.JLabel interfacesTxt;
    private javax.swing.JLabel methodCountLbl;
    private javax.swing.JLabel methodCountTxt;
    private javax.swing.JLabel superClassNameLbl;
    private javax.swing.JLabel superClassNameTxt;
    // End of variables declaration//GEN-END:variables
}
