/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * ConstantPoolViewPanel.java
 *
 * Created on 15-jan-2012, 21:35:40
 */
package net.aurora.sorcery.ui.panel;

import net.aurora.sorcery.ui.frame.ClassViewerForm;

/**
 *
 * @author Devel
 */
public class ConstantPoolViewPanel extends javax.swing.JPanel {
    private ClassViewerForm parent;
    
    /** Creates new form ConstantPoolViewPanel */
    public ConstantPoolViewPanel(ClassViewerForm parent) {
        initComponents();
        this.parent = parent;
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 713, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 426, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents
    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
