/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * ClassSelectionDialog.java
 *
 * Created on 15-jan-2012, 12:39:26
 */
package net.aurora.sorcery.ui.dialog;

import net.aurora.sorcery.ClassContainer;
import net.aurora.sorcery.Sorcery;
import net.aurora.sorcery.ui.SorceryUI;
import serp.bytecode.BCClass;

/**
 * @author Devel
 */
public class ClassSelectionDialog extends javax.swing.JFrame {
    private SorceryUI parent;

    /**
     * Creates new form ClassSelectionDialog
     */
    public ClassSelectionDialog(SorceryUI parent) {
        this.parent = parent;

        initComponents();

        ClassContainer classContainer = Sorcery.getSorcery().getClassContainer();
        classList.setListData(classContainer.getClasses());
    }

    /**
     * This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">
    private void initComponents() {

        classLbl = new javax.swing.JLabel();
        classListScrollPane = new javax.swing.JScrollPane();
        classList = new javax.swing.JList();
        okButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        classLbl.setText("Available classes:");

        classListScrollPane.setViewportView(classList);

        okButton.setText("OK");
        okButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                okButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(classListScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 393, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(classLbl))
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addContainerGap(356, Short.MAX_VALUE)
                                .addComponent(okButton)
                                .addContainerGap())
        );
        layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(classLbl)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(classListScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 17, Short.MAX_VALUE)
                                .addComponent(okButton))
        );

        pack();
    }// </editor-fold>

    private void okButtonActionPerformed(java.awt.event.ActionEvent evt) {
        this.parent.initializeClass((BCClass)classList.getSelectedValue());
        this.dispose();
    }

    // Variables declaration - do not modify
    private javax.swing.JLabel classLbl;
    private javax.swing.JList classList;
    private javax.swing.JScrollPane classListScrollPane;
    private javax.swing.JButton okButton;
    // End of variables declaration
}
