package net.aurora.ui;

import net.aurora.bot.Bot;

import javax.swing.*;

/**
 *
 * @author Devel
 */
public class SimpleFrame extends javax.swing.JFrame {

    /** Creates new form SimpleFrame */
    public SimpleFrame() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">
    private void initComponents() {

        clientTabbedPane = new javax.swing.JTabbedPane();
        topMenuBar = new javax.swing.JMenuBar();
        fileMenu = new javax.swing.JMenu();
        newClientMenuItem = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Aurora");

        clientTabbedPane.setTabLayoutPolicy(javax.swing.JTabbedPane.SCROLL_TAB_LAYOUT);

        fileMenu.setText("File");

        newClientMenuItem.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_N, java.awt.event.InputEvent.CTRL_MASK));
        newClientMenuItem.setText("New client");
        newClientMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                newClientMenuItemActionPerformed(evt);
            }
        });
        fileMenu.add(newClientMenuItem);

        topMenuBar.add(fileMenu);

        setJMenuBar(topMenuBar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(clientTabbedPane, javax.swing.GroupLayout.DEFAULT_SIZE, 770, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(clientTabbedPane, javax.swing.GroupLayout.DEFAULT_SIZE, 543, Short.MAX_VALUE)
        );

        java.awt.Dimension screenSize = java.awt.Toolkit.getDefaultToolkit().getScreenSize();
        setBounds((screenSize.width-786)/2, (screenSize.height-602)/2, 786, 602);
    }// </editor-fold>


    private void newClientMenuItemActionPerformed(java.awt.event.ActionEvent evt) {
        SwingUtilities.invokeLater(new Runnable() {
            public void run() {
                Bot bot = new Bot();
                clientTabbedPane.addTab("Client", bot.getLoader().getApplet());
            }
        });
    }


    // Variables declaration - do not modify                     
    private javax.swing.JTabbedPane clientTabbedPane;
    private javax.swing.JMenu fileMenu;
    private javax.swing.JMenuItem newClientMenuItem;
    private javax.swing.JMenuBar topMenuBar;
    // End of variables declaration                   
}
