/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * UI.java
 *
 * Created on 29-nov-2011, 4:38:42
 */
package net.aurora.ui;

import net.aurora.bot.Bot;

import javax.swing.*;
import java.applet.Applet;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import net.aurora.sorcery.Sorcery;
import net.aurora.sorcery.ui.SorceryFrame;

/**
 * @author Devel
 */
public class UI extends javax.swing.JFrame {

    /**
     * Creates new form UI
     */
    public UI() {
        initComponents();
        setTitle("Aurora");
        setSize(1024, 768);
    }

    /**
     * This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">
    private void initComponents() {

        appletPanel = new javax.swing.JPanel();
        debugScrollPane = new javax.swing.JScrollPane();
        debugList = new javax.swing.JList();
        menuBar = new javax.swing.JMenuBar();
        fileMenu = new javax.swing.JMenu();
        closeMenuItem = new javax.swing.JMenuItem();
        editMenu = new javax.swing.JMenu();
        oglSettingsItem = new javax.swing.JMenuItem();
        botSettingsItem = new javax.swing.JMenuItem();
        editMenuSeperator = new javax.swing.JPopupMenu.Separator();
        accountsItem = new javax.swing.JMenuItem();
        randomsItem = new javax.swing.JMenuItem();
        breakhandlerItem = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout appletPanelLayout = new javax.swing.GroupLayout(appletPanel);
        appletPanel.setLayout(appletPanelLayout);
        appletPanelLayout.setHorizontalGroup(
                appletPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGap(0, 768, Short.MAX_VALUE)
        );
        appletPanelLayout.setVerticalGroup(
                appletPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGap(0, 533, Short.MAX_VALUE)
        );

        debugScrollPane.setViewportView(debugList);

        fileMenu.setText("File");

        closeMenuItem.setText("Close");
        fileMenu.add(closeMenuItem);

        menuBar.add(fileMenu);

        editMenu.setText("Edit");

        oglSettingsItem.setText("OpenGL Settings");
        oglSettingsItem.setEnabled(false);
        editMenu.add(oglSettingsItem);

        botSettingsItem.setText("Bot Settings");
        editMenu.add(botSettingsItem);
        editMenu.add(editMenuSeperator);

        accountsItem.setText("Configure accounts");
        editMenu.add(accountsItem);

        randomsItem.setText("Configure randoms");
        editMenu.add(randomsItem);

        breakhandlerItem.setText("Configure breakhandler");
        editMenu.add(breakhandlerItem);

        menuBar.add(editMenu);

        toolsMenu = new JMenu("Tools");

        sorceryItem = new JMenuItem("Sorcery Explorer");
        sorceryItem.addActionListener(new ActionListener() {

            public void actionPerformed(ActionEvent e) {
                new SorceryFrame(Sorcery.getSorcery()).setVisible(true);
            }

        });
        toolsMenu.add(sorceryItem);

        menuBar.add(toolsMenu);

        setJMenuBar(menuBar);

        Bot.getSingleton().init();
        Applet applet = Bot.getSingleton().getApplet();

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(applet, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(debugScrollPane, javax.swing.GroupLayout.DEFAULT_SIZE, 768, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addComponent(applet, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGap(0, 0, 0)
                                .addComponent(debugScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>

    // Variables declaration - do not modify
    private javax.swing.JMenuItem accountsItem;
    private javax.swing.JPanel appletPanel;
    private javax.swing.JMenuItem botSettingsItem;
    private javax.swing.JMenuItem breakhandlerItem;
    private javax.swing.JMenuItem closeMenuItem;
    private javax.swing.JList debugList;
    private javax.swing.JScrollPane debugScrollPane;
    private JMenu toolsMenu;
    private JMenuItem sorceryItem;
    private javax.swing.JMenu editMenu;
    private javax.swing.JPopupMenu.Separator editMenuSeperator;
    private javax.swing.JMenu fileMenu;
    private javax.swing.JMenuBar menuBar;
    private javax.swing.JMenuItem oglSettingsItem;
    private javax.swing.JMenuItem randomsItem;
    // End of variables declaration
}
